<?php

/**
 * Zend_Db_Table based simpe ORM for the agent_permissions table
 * Autogenerated by db.php:
 *   timestamp: Sat, 13 Nov 10 15:24:19 -0500
 *   database:  openzis
 *   host:      192.168.1.22
 * 
 * @version $Id$
 */
class AgentPermissions extends Zend_Db_Table
{
    /**
     * Table name
     * 
     * @var string
     */
#    protected $_schema = 'OPENZIS';
	protected $_name = 'AGENT_PERMISSIONS';

    /**
     * Primary key field
     * 
     * @var string
     */
    protected $_primary = 'permission_id';

    /**
     * List of columns
     * 
     * @var array
     */
    protected $_cols = array(
	'permission_id' => 'permission_id',
	'agent_id'		=> 'agent_id',
	'context_id'	=> 'context_id',
	'object_id'		=> 'object_id',
	'can_provide'	=> 'can_provide',
	'can_subscribe' => 'can_subscribe'
	'can_add'		=> 'can_add',
	'can_update'	=> 'can_update',
	'can_delete'	=> 'can_delete',
	'can_request'	=> 'can_request',
	'can_respond'	=> 'can_respond',
	'zone_id'		=> 'zone_id'	
    );
}