<?php

/**
 * Zend_Db_Table based simpe ORM for the agent_responder table
 * Autogenerated by db.php:
 *   timestamp: Sat, 13 Nov 10 15:24:19 -0500
 *   database:  openzis
 *   host:      192.168.1.22
 * 
 * @version $Id$
 */
class AgentResponder extends Zend_Db_Table
{
    /**
     * Table name
     * 
     * @var string
     */
#    protected $_schema = 'OPENZIS';
	protected $_name = 'AGENT_RESPONDER';

    /**
     * Primary key field
     * 
     * @var string
     */
    protected $_primary = 'responder_id';

    /**
     * List of columns
     * 
     * @var array
     */
    protected $_cols = array(
		'responder_id'=>'responder_id', 
		'agent_id'=>'agent_id', 
		'object_type_id'=>'object_type_id', 
		'responder_timestamp'=>'responder_timestamp', 
		'context_id'=>'context_id', 
		'zone_id'=>'zone_id'
    );
}