<?php

/**
 * Zend_Db_Table based simpe ORM for the error_log table
 * Autogenerated by db.php:
 *   timestamp: Sat, 13 Nov 10 15:24:19 -0500
 *   database:  openzis
 *   host:      192.168.1.22
 * 
 * @version $Id$
 */
class ErrorLog extends Zend_Db_Table
{
    /**
     * Table name
     * 
     * @var string
     */
#    protected $_schema = 'OPENZIS';
	protected $_name = 'ERROR_LOG';

    /**
     * Primary key field
     * 
     * @var string
     */
    protected $_primary = 'error_id';

    /**
     * List of columns
     * 
     * @var array
     */
    protected $_cols = array(
		'error_id'=>'error_id', 
		'short_error_desc'=>'short_error_desc', 
		'long_error_desc'=>'long_error_desc', 
		'error_location'=>'error_location', 
		'error_timestamp'=>'error_timestamp', 
		'zone_id'=>'zone_id', 
		'agent_id'=>'agent_id', 
		'context_id'=>'context_id', 
		'archived' => 'archived'
    );
}