<?php

/**
 * Zend_Db_Table based simpe ORM for the event_status table
 * Autogenerated by db.php:
 *   timestamp: Sat, 13 Nov 10 15:24:19 -0500
 *   database:  openzis
 *   host:      192.168.1.22
 * 
 * @version $Id$
 */
class TB_EventStatus extends Zend_Db_Table
{
    /**
     * Table name
     * 
     * @var string
     */
#    protected $_schema = 'OPENZIS';
	protected $_name = 'EVENT_STATUS';

    /**
     * Primary key field
     * 
     * @var string
     */
    protected $_primary = 'status_id';

    /**
     * List of columns
     * 
     * @var array
     */
    protected $_cols = array(
	'status_id'=>'status_id', 
	'status_desc'=>'status_desc'
    );
}