<?php

/**
 * Zend_Db_Table based simpe ORM for the push_handler table
 * Autogenerated by db.php:
 *   timestamp: Sat, 13 Nov 10 15:24:19 -0500
 *   database:  openzis
 *   host:      192.168.1.22
 * 
 * @version $Id$
 */
class TB_PushHandler extends Zend_Db_Table
{
    /**
     * Table name
     * 
     * @var string
     */
#    protected $_schema = 'OPENZIS';	
	protected $_name = 'PUSH_HANDLER';

    /**
     * Primary key field
     * 
     * @var string
     */
    protected $_primary = '';

    /**
     * List of columns
     * 
     * @var array
     */
    protected $_cols = array(
		'ZONE_ID'=>'ZONE_ID', 
		'CONTEXT_ID'=>'CONTEXT_ID', 
		'PUSH_RUNNING'=>'PUSH_RUNNING', 
		'LAST_START'=>'LAST_START', 
		'LAST_STOP'=>'LAST_STOP', 
		'PHP_PID'=>'PHP_PID', 
		'SLEEP_TIME_SECONDS'=>'SLEEP_TIME_SECONDS'
    );
}